### ISSUE TITLE
Split into @nuxtjs/design-tokens and @nuxtjs/theme-config

### ISSUE THREAD

**Issue by atinux** [Tahul/nuxt-theme-kit#3]
Like discussed with @pi0 

I guess we can also move them right away in nuxt-community, I am also fine having them in `nuxt-themes` but better to have modules in `nuxt-community`.

**Comment by pi0** [comment]
👍🏼  for design tokens in the community. Since theme-config is probably for the short-term, I would suggest simplifying the current module and renaming it to `nuxt-theme-config`.
